### ISSUE TITLE
Add support for Storage Classes

### ISSUE THREAD

**Issue by Falconx1000** [Addyvan/valheim-k8s#21]
Add support for using kubernetes storage classes.
With only host mount support the server has be pinned to the same host. (partial fix #14 )
Could be setup similar to https://github.com/bitnami/charts/tree/master/bitnami/mysql

**Comment by daviddob** [comment]
I have an implementation of this working - just doing some testing and ill PR it likely tomorrow night. Thoughts on the below configuration? I tried to keep it in line with the existing chart config spec.

```yaml
storage:
  kind: persistentVolumeClaim
  pvc:
    storageClassName: vsphere-csi
    size: 10Gi
```

**Comment by Falconx1000** [comment]
I can try testing it out whenever it is updated. I haven't had a chance to look at any of the code yet but I was thinking something like that

**Comment by motmot80** [comment]
Yes seems to be pretty simple in my case.

Maybe you could just add the option to reference an external self created pvc by name:

```
       {{ if eq .Values.storage.kind "pvc" }}
        volumeMounts:
        - mountPath: /config
          name: gamefiles
        resources: {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: gamefiles
        persistentVolumeClaim:
            claimName: {{ .Values.storage.pvc.name }}
       {{ end }}

```

```
  --set storage.kind=pvc \
  --set storage.pvc.name=my-self-created-cloud-provider-pvc
```

So everyone could create custom and provider specific pvcs.
And maybe create an example **pvc.yaml**

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-valheim
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```
