### ISSUE TITLE
serverStorage isn't provisioned 

### ISSUE THREAD

**Issue by kamilgregorczyk** [Addyvan/valheim-k8s#40]
Hello, I'm passing such values:

```
worldName: "ZadupieNowe3"
serverName: "NieliszCycowNiemce"
password: "secret"
storage:
  kind: "persistentVolumeClaim"
  pvc:
    storageClassName: "longhorn"
    size: 5Gi

serverStorage:
  kind: "persistentVolumeClaim"
  pvc:
    storageClassName: "longhorn"
    size: 5Gi
```

and only storage is created, serverStorage isn't provisioned for some reason 

```
➜  ~ kubectl -n valheim get pvc
NAME                        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
valheim-server-world-data   Bound    pvc-4ef318bf-0730-4ba9-81cc-79238c14349d   5Gi        RWO            longhorn       21h
```
